api_key: 'AIzaSyD9JV5sxIsgahtlso70sTjBkG7haW9LcBs'

# WARNING: 
# For each keyword you add to the queries section below,
# it will take more time and more money to query, so be careful with this.
queries:
  - tobacco
  - gas station
  - convenience store
  - liquor store
  - pharmacy
  - vape
  - cbd

keywords:
  - marlboro
  - papers
  - cigs,
  - camel
  - bong
  - pipe
  - newport
  - cigarette
  - fog
  - cigar
  - cloud
  - tobacco
  - smoke
  - snuff
  - loose leaf
  - dip
  - chew
  - vape
  - cdb
  - delta
  - smoker
  - cigs
  - vapor
  - leafs
  - leaf
  - juul
  - hookah
  - nicotine
  - roll
  - puff
  - swisher
  - black and mild
  - grizzly
  - skoal
  - blunt
  - backwoods
  - raw papers
  - kush
  - green
  - herb
  - splitt
  - wax
  - shisha
  - blaze
  - hit
  - smoking blend
  - shatter
  - menthol
  - rolling paper
  - rolling
  - shatter
  - dab
  - edibles
  - tincture
  - oil
  - disposable
  - mod
  - cartridge
  - pen
  - zig zag
