api_key: 'your api here'

# WARNING: 
# For each keyword you add to the queries section below,
# it will take more time and more money to query, so be careful with this.
queries:
  - tobacco
  - gas station
  - convenience store
  - liquor store
  - pharmacy

keywords:
  - marlboro
  - camel
  - newport
  - vape
  - smoke
  - cigarette
  - fog
  - cigar
  - cloud
  - tobacco
  - smoke
  - snuff
  - loose leaf
  - chewing tobacco
  - vape
  - vapor
  - smoke shop
  - smoker
  - cigs

